# controllers are implemented as services
# no annotations are used

WSLDemoBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: demo_controller:indexAction }
    
WSLDemoBundle_testpage:
    pattern:  /test/{name}
    defaults: { _controller: demo_controller:indexAction }    