parameters:
#    wsl_demo.example.class: WSL\DemoBundle\Example

services:
#    wsl_demo.example:
#        class: %wsl_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
